services:
  - type: web
    name: chartlink-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: "5000"
